alter table GESTIONACTIVIDADES_FACTURA_ACTIVIDAD_LINK add constraint FK_GFAL_FACTURA foreign key (FACTURA_ID) references GESTIONACTIVIDADES_FACTURA (ID);
alter table GESTIONACTIVIDADES_FACTURA_ACTIVIDAD_LINK add constraint FK_GFAL_ACTIVIDAD foreign key (ACTIVIDAD_ID) references GESTIONACTIVIDADES_ACTIVIDAD (ID);
