-- begin GESTIONACTIVIDADES_RESPONSABLE
create unique index IDX_GESTIONACTIVIDADES_RESPONSABLE_UNIQ_DOC_ID on GESTIONACTIVIDADES_RESPONSABLE (DOC_ID) ^
-- end GESTIONACTIVIDADES_RESPONSABLE
-- begin GESTIONACTIVIDADES_ALUMNO
alter table GESTIONACTIVIDADES_ALUMNO add constraint FK_GESTIONACTIVIDADES_ALUMNO_RESPONSABLE_ID foreign key (RESPONSABLE_ID) references GESTIONACTIVIDADES_RESPONSABLE(ID)^
create index IDX_GESTIONACTIVIDADES_ALUMNO_RESPONSABLE on GESTIONACTIVIDADES_ALUMNO (RESPONSABLE_ID)^
-- end GESTIONACTIVIDADES_ALUMNO

-- begin GESTIONACTIVIDADES_FACTURA
alter table GESTIONACTIVIDADES_FACTURA add constraint FK_GESTIONACTIVIDADES_FACTURA_RESPONSABLE_ID foreign key (RESPONSABLE_ID) references GESTIONACTIVIDADES_RESPONSABLE(ID)^
create index IDX_GESTIONACTIVIDADES_FACTURA_RESPONSABLE on GESTIONACTIVIDADES_FACTURA (RESPONSABLE_ID)^
-- end GESTIONACTIVIDADES_FACTURA

-- begin GESTIONACTIVIDADES_FACTURA_ACTIVIDAD_LINK
alter table GESTIONACTIVIDADES_FACTURA_ACTIVIDAD_LINK add constraint FK_GFAL_FACTURA foreign key (FACTURA_ID) references GESTIONACTIVIDADES_FACTURA (ID)^
alter table GESTIONACTIVIDADES_FACTURA_ACTIVIDAD_LINK add constraint FK_GFAL_ACTIVIDAD foreign key (ACTIVIDAD_ID) references GESTIONACTIVIDADES_ACTIVIDAD (ID)^
-- end GESTIONACTIVIDADES_FACTURA_ACTIVIDAD_LINK
-- begin GESTIONACTIVIDADES_ALUMNO_ACTIVIDAD_LINK
alter table GESTIONACTIVIDADES_ALUMNO_ACTIVIDAD_LINK add constraint FK_GAAL_ALUMNO foreign key (ALUMNO_ID) references GESTIONACTIVIDADES_ALUMNO (ID)^
alter table GESTIONACTIVIDADES_ALUMNO_ACTIVIDAD_LINK add constraint FK_GAAL_ACTIVIDAD foreign key (ACTIVIDAD_ID) references GESTIONACTIVIDADES_ACTIVIDAD (ID)^
-- end GESTIONACTIVIDADES_ALUMNO_ACTIVIDAD_LINK
